### ISSUE TITLE
please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [TheCodeMonks/Notzz-App#47]
could you please increase `versionCode` when making a new release? That's what Android tells the versions apart by – so as today's release still has `versionCode: 1` Android won't consider it as an update for those having the previous version installed. Thanks!

**Comment by Spikeysanju** [comment]
@IzzySoft Sure man! Thanks for the info

**Comment by Spikeysanju** [comment]
Haha Sorry my bad 🤣 . Every time I forgot to update the version code. Thanks for the reminder 👍

**Comment by Spikeysanju** [comment]
It was fixed in the latest commit buddy ✅ . Thanks for the reminder. Have a great day!

**Comment by IzzySoft** [comment]
:rofl: Please reopen again, you once more forgot `versionCode` – it's still set to `1` but should be, err, `4` meanwhile?

```gradle
    defaultConfig {
        applicationId "thecodemonks.org.nottzapp"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.3.3"
```

Remember:

* `versionName`: what's displayed to the user (and most likely will be used when reporting issues)
* `versionCode`: what Android uses internally to tell versions apart; this is the most important one to always increase with each new release

**Comment by IzzySoft** [comment]
@Spikeysanju my updater still gives me daily alerts because of the `versionCode`, so I'm disabling the update check for now. Please drop me a note once you fixed it, @Spikeysanju – thanks!

**Comment by IzzySoft** [comment]
@Spikeysanju  any chance? Btw it's irritating that the APK at release tag v1.3 still identifies as 0.1.3 :wink:

**Comment by IzzySoft** [comment]
@Spikeysanju again you forgot: my updater just fetched a new version last night (we're at 1.4 now), and it still shows `versionCode: 1`. None of your users will ever receive update notifications, or be otherwise aware of new versions: even if they look at their F-Droid app, it will seem to them that they have the latest version already installed – as Android thinks so.

Maybe one year after reporting, can we get this finally fixed, please? Thanks!

**Comment by Spikeysanju** [comment]
@IzzySoft  Oops I'm sorry I forgot to update the version everytime 😬.

 I've updated the `version code` to `4`. Please check it out. Thanks for bringing this up 🙌
 
 Checkout the latest 👇 
  [release](https://github.com/TheCodeMonks/Notzz-App/releases/download/v1.4/Notzz.apk) 
  
  Checkout latest pr 👇 
  #241

**Comment by IzzySoft** [comment]
Thanks! That one looks good. Just downloaded it manually (as my updater was now fooled by the fact it already had processed that tag) and checked. Will become visible in about 1.5h from now (with the next sync).

Will it now work well for the next releases, too? :smiley:

**Comment by Spikeysanju** [comment]
Yeah sure, I hope I will remember this for sure next time 😄. Have a great day buddy!

**Comment by IzzySoft** [comment]
You too, friend! And should you forget again, I'll come and remind you :laughing:
